version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:5000"
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - mariadb
    restart: always
    volumes:
      - .:/root

  lineapi:
    build:
      context: ./ 
      dockerfile: open-line
    restart: always  
    environment:
      TZ: Asia/Bangkok

  lineapi2:
    build:
      context: ./ 
      dockerfile: reed-check
    restart: always 
    environment:
      TZ: Asia/Bangkok

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
      MYSQL_DATABASE: jobintosh
      MYSQL_USER: jobintosh
      MYSQL_PASSWORD: 6u&h^j=U0w)bc[f
      TZ: Asia/Bangkok
    ports:
    - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
    ports:
      - 8080:80