version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "80:5000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=6u&h^j=U0w)bc[f
      - MYSQL_DATABASE=flask_db
      - TZ=Asia/Bangkok
    depends_on:
      - mariadb
    restart: always

  lineapi:
    build:
      context: ./ 
      dockerfile: dockerline
    container_name: lineapi
    restart: always  

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
      MYSQL_DATABASE: jobintosh
      MYSQL_USER: jobintosh
      MYSQL_PASSWORD: 6u&h^j=U0w)bc[f
      TZ: Asia/Bangkok
    ports:
    - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
    ports:
      - 8080:80