version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always  # Add this line to set the restart policy to "always"
    environment:
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
      MYSQL_DATABASE: jobintosh
      MYSQL_USER: jobintosh
      MYSQL_PASSWORD: 6u&h^j=U0w)bc[f
      TZ: Asia/Bangkok
    ports:
    - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  # lineapi:
  #   build:
  #     context: ./ 
  #     dockerfile: dockerline
  #   container_name: lineapi
  #   restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always 
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 6u&h^j=U0w)bc[f
    ports:
      - 8080:80
